sudo apt-get install python3-pip
sudo pip3 install readline
sudo apt install nmap
sudo apt install ffuf
sudo apt install wfuzz
sudo apt install nuclei
sudo apt install seclists
sudo apt install smbclient
sudo apt install mount